# Generated by Django 6.0.5 on 2026-06-03 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('referral_type', models.CharField(choices=[('internal', 'Internal - Same Facility'), ('external', 'External - Different Facility'), ('emergency', 'Emergency Transfer'), ('specialist', 'Specialist Consultation')], max_length=20)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', max_length=20)),
                ('referring_facility', models.CharField(max_length=200)),
                ('referring_department', models.CharField(blank=True, max_length=200)),
                ('receiving_facility', models.CharField(max_length=200)),
                ('receiving_department', models.CharField(blank=True, max_length=200)),
                ('receiving_doctor', models.CharField(blank=True, max_length=200)),
                ('receiving_contact', models.CharField(blank=True, max_length=20)),
                ('reason_for_referral', models.TextField()),
                ('clinical_summary', models.TextField()),
                ('provisional_diagnosis', models.TextField()),
                ('investigations_done', models.TextField(blank=True)),
                ('treatment_given', models.TextField(blank=True)),
                ('referral_letter', models.FileField(blank=True, null=True, upload_to='referrals/')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='referrals/attachments/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='referrals/qr/')),
                ('access_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('feedback_from_receiving', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_referrals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_referrals', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_outgoing', to='patients.patient')),
                ('referring_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='visits.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_notes', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='referrals.referral')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referral_number'], name='referrals_r_referra_13ce98_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['patient', 'status'], name='referrals_r_patient_fc132b_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referring_facility', 'receiving_facility'], name='referrals_r_referri_c9dbc0_idx'),
        ),
    ]
