# Generated by Django 6.0.5 on 2026-06-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_auditlog_ip_address_alter_auditlog_user_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
