# Generated by Django 6.0.5 on 2026-06-03 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('drug_code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('antibiotic', 'Antibiotic'), ('analgesic', 'Analgesic'), ('antihypertensive', 'Antihypertensive'), ('antidiabetic', 'Antidiabetic'), ('antimalarial', 'Antimalarial'), ('antiretroviral', 'Antiretroviral'), ('vaccine', 'Vaccine'), ('vitamin', 'Vitamin/Supplement'), ('cns', 'CNS Drug'), ('respiratory', 'Respiratory Drug'), ('gi', 'Gastrointestinal Drug'), ('other', 'Other')], max_length=20)),
                ('drug_form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('ointment', 'Ointment/Cream'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('suppository', 'Suppository'), ('suspension', 'Suspension')], max_length=20)),
                ('strength', models.CharField(help_text='e.g., 500mg, 10mg/ml', max_length=100)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_stock', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=100)),
                ('reorder_quantity', models.IntegerField(default=500)),
                ('requires_prescription', models.BooleanField(default=True)),
                ('is_controlled', models.BooleanField(default=False, help_text='Controlled substance')),
                ('common_allergies', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True)),
                ('side_effects', models.TextField(blank=True)),
                ('precautions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['generic_name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('dosage', models.CharField(help_text='e.g., 1 tablet', max_length=100)),
                ('frequency', models.CharField(help_text='e.g., Twice daily', max_length=100)),
                ('duration', models.CharField(help_text='e.g., 7 days', max_length=100)),
                ('quantity', models.IntegerField()),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intravenous'), ('im', 'Intramuscular'), ('sc', 'Subcutaneous'), ('topical', 'Topical'), ('inhalation', 'Inhalation'), ('rectal', 'Rectal')], default='oral', max_length=20)),
                ('special_instructions', models.TextField(blank=True)),
                ('food_instructions', models.CharField(blank=True, help_text='Take with/without food', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Dispensed'), ('dispensed', 'Fully Dispensed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('dispensed_quantity', models.IntegerField(default=0)),
                ('refills_allowed', models.IntegerField(default=0)),
                ('refills_remaining', models.IntegerField(default=0)),
                ('prescribed_at', models.DateTimeField(auto_now_add=True)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('clinical_notes', models.TextField(blank=True)),
                ('cancelled_reason', models.TextField(blank=True)),
                ('dispensed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='pharmacy.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
                ('prescribing_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='visits.visit')),
            ],
            options={
                'ordering': ['-prescribed_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('receive', 'Stock Received'), ('issue', 'Stock Issued'), ('adjustment', 'Stock Adjustment'), ('return', 'Stock Return'), ('expiry', 'Expired Stock')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('stock_before', models.IntegerField()),
                ('stock_after', models.IntegerField()),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to=settings.AUTH_USER_MODEL)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pharmacy.medication')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='pharmacy.prescription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescription_number'], name='pharmacy_pr_prescri_2aaaee_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', 'status'], name='pharmacy_pr_patient_903ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['prescribed_at'], name='pharmacy_pr_prescri_117fa9_idx'),
        ),
    ]
