# Generated by Django 6.0.5 on 2026-06-03 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('specimen_type', models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('stool', 'Stool'), ('sputum', 'Sputum'), ('swab', 'Swab'), ('tissue', 'Tissue'), ('cerebrospinal', 'Cerebrospinal Fluid'), ('pleural', 'Pleural Fluid'), ('ascitic', 'Ascitic Fluid'), ('other', 'Other')], max_length=20)),
                ('normal_range', models.CharField(blank=True, help_text='Normal reference range', max_length=200)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('turnaround_time', models.IntegerField(default=24, help_text='Turnaround time in hours')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_fasting', models.BooleanField(default=False)),
                ('fasting_hours', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabTestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Lab Test Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT - Immediate')], default='routine', max_length=20)),
                ('clinical_notes', models.TextField(blank=True, help_text='Relevant clinical information')),
                ('diagnosis', models.TextField(blank=True)),
                ('specimen_type', models.CharField(max_length=50)),
                ('specimen_collected_at', models.DateTimeField(blank=True, null=True)),
                ('specimen_quality', models.CharField(blank=True, max_length=100)),
                ('started_processing_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_value', models.TextField(blank=True)),
                ('result_numeric', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('result_unit', models.CharField(blank=True, max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=200)),
                ('interpretation', models.TextField(blank=True)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Collection'), ('collected', 'Specimen Collected'), ('processing', 'Processing'), ('verified', 'Verified'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tests', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='patients.patient')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_tests', to=settings.AUTH_USER_MODEL)),
                ('requesting_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to=settings.AUTH_USER_MODEL)),
                ('specimen_collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_specimens', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tests', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='visits.visit')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='laboratory.labtest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=200)),
                ('result_value', models.CharField(max_length=200)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('reference_range', models.CharField(blank=True, max_length=200)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('flag', models.CharField(blank=True, help_text='H=High, L=Low, A=Abnormal', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_results', to='laboratory.labrequest')),
            ],
            options={
                'ordering': ['component_name'],
            },
        ),
        migrations.AddField(
            model_name='labtest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='laboratory.labtestcategory'),
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['request_number'], name='laboratory__request_17ee1a_idx'),
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['patient', 'status'], name='laboratory__patient_2e783f_idx'),
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['status'], name='laboratory__status_89fa49_idx'),
        ),
        migrations.AddIndex(
            model_name='labrequest',
            index=models.Index(fields=['priority'], name='laboratory__priorit_242687_idx'),
        ),
    ]
