# Generated by Django 6.0.5 on 2026-06-03 09:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('estimated_wait_time', models.IntegerField(default=0, help_text='Minutes')),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_assignments', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage_queue', to='visits.visit')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('respiratory_rate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('systolic_bp', models.IntegerField(blank=True, null=True)),
                ('diastolic_bp', models.IntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('priority', models.CharField(choices=[('resuscitation', 'Resuscitation - Immediate life-threatening'), ('emergency', 'Emergency - Very urgent'), ('urgent', 'Urgent - Urgent'), ('less_urgent', 'Less Urgent - Standard'), ('non_urgent', 'Non Urgent - Can wait')], max_length=20)),
                ('colour_code', models.CharField(editable=False, max_length=10)),
                ('triage_score', models.IntegerField(default=0, help_text='Calculated triage score 0-10')),
                ('complaint_category', models.CharField(blank=True, max_length=100)),
                ('mechanism_of_injury', models.TextField(blank=True)),
                ('avpu_score', models.CharField(choices=[('A', 'Alert'), ('V', 'Responds to Voice'), ('P', 'Responds to Pain'), ('U', 'Unresponsive')], default='A', max_length=1)),
                ('glasgow_coma_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(15)])),
                ('pupil_response', models.CharField(blank=True, max_length=100)),
                ('pain_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('pain_location', models.CharField(blank=True, max_length=200)),
                ('breathing_difficulty', models.BooleanField(default=False)),
                ('breath_sounds', models.CharField(blank=True, max_length=200)),
                ('use_accessory_muscles', models.BooleanField(default=False)),
                ('capillary_refill', models.IntegerField(blank=True, help_text='Seconds', null=True)),
                ('peripheral_pulses', models.CharField(blank=True, max_length=100)),
                ('skin_turgor', models.CharField(blank=True, max_length=100)),
                ('limb_movement', models.CharField(blank=True, max_length=200)),
                ('speech', models.CharField(blank=True, max_length=200)),
                ('rash', models.BooleanField(default=False)),
                ('rash_description', models.TextField(blank=True)),
                ('bruises', models.BooleanField(default=False)),
                ('swelling', models.BooleanField(default=False)),
                ('swelling_location', models.CharField(blank=True, max_length=200)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('pregnancy_weeks', models.IntegerField(blank=True, null=True)),
                ('is_diabetic', models.BooleanField(default=False)),
                ('is_hypertensive', models.BooleanField(default=False)),
                ('is_asthmatic', models.BooleanField(default=False)),
                ('is_immunocompromised', models.BooleanField(default=False)),
                ('is_elderly', models.BooleanField(default=False, help_text='Age > 65')),
                ('is_child', models.BooleanField(default=False, help_text='Age < 5')),
                ('is_trauma_patient', models.BooleanField(default=False)),
                ('oxygen_given', models.BooleanField(default=False)),
                ('oxygen_flow_rate', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('iv_line_placed', models.BooleanField(default=False)),
                ('medications_given', models.TextField(blank=True)),
                ('disposition', models.CharField(blank=True, max_length=100)),
                ('referred_to', models.CharField(blank=True, max_length=200)),
                ('triage_notes', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('triage_start', models.DateTimeField(auto_now_add=True)),
                ('triage_completed', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_triages', to=settings.AUTH_USER_MODEL)),
                ('triage_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_assessments', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage_assessment', to='visits.visit')),
            ],
            options={
                'verbose_name_plural': 'Triage Assessments',
                'indexes': [models.Index(fields=['visit'], name='triage_tria_visit_i_0306b4_idx'), models.Index(fields=['priority'], name='triage_tria_priorit_f67ed2_idx'), models.Index(fields=['triage_start'], name='triage_tria_triage__dd18d0_idx')],
            },
        ),
    ]
