# Generated by Django 6.0.5 on 2026-06-03 09:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('mrn_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('qr_code_data', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=10)),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('maiden_name', models.CharField(blank=True, max_length=100)),
                ('id_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('alien_id', 'Alien ID'), ('birth_cert', 'Birth Certificate'), ('none', 'None')], default='national_id', max_length=20)),
                ('identification_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('passport_number', models.CharField(blank=True, max_length=20)),
                ('birth_certificate_number', models.CharField(blank=True, max_length=50)),
                ('nhif_number', models.CharField(blank=True, db_index=True, max_length=20)),
                ('other_id', models.CharField(blank=True, max_length=100)),
                ('phone_primary', models.CharField(db_index=True, max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('phone_secondary', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('alternative_email', models.EmailField(blank=True, max_length=254)),
                ('date_of_birth', models.DateField()),
                ('age', models.PositiveIntegerField(editable=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], db_index=True, max_length=1)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated')], default='single', max_length=20)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('county', models.CharField(blank=True, db_index=True, max_length=100)),
                ('sub_county', models.CharField(blank=True, max_length=100)),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('sub_location', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('physical_address', models.TextField(blank=True)),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('emergency_contact_alternative', models.CharField(blank=True, max_length=15)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('employer', models.CharField(blank=True, max_length=200)),
                ('employer_phone', models.CharField(blank=True, max_length=15)),
                ('employer_address', models.TextField(blank=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=100)),
                ('insurance_number', models.CharField(blank=True, max_length=100)),
                ('insurance_valid_until', models.DateField(blank=True, null=True)),
                ('next_of_kin_name', models.CharField(blank=True, max_length=200)),
                ('next_of_kin_relationship', models.CharField(blank=True, max_length=100)),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=15)),
                ('next_of_kin_address', models.TextField(blank=True)),
                ('is_deceased', models.BooleanField(default=False)),
                ('date_of_death', models.DateField(blank=True, null=True)),
                ('cause_of_death', models.TextField(blank=True)),
                ('has_allergies', models.BooleanField(default=False)),
                ('has_chronic_diseases', models.BooleanField(default=False)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('is_disabled', models.BooleanField(default=False)),
                ('disability_type', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_merged', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL)),
                ('merged_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_patients', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen', models.CharField(max_length=200)),
                ('allergen_type', models.CharField(blank=True, max_length=100)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('life_threatening', 'Life Threatening')], max_length=20)),
                ('reaction', models.CharField(choices=[('rash', 'Rash/Hives'), ('swelling', 'Swelling'), ('difficulty_breathing', 'Difficulty Breathing'), ('anaphylaxis', 'Anaphylaxis'), ('nausea', 'Nausea/Vomiting'), ('diarrhea', 'Diarrhea'), ('headache', 'Headache'), ('fever', 'Fever'), ('other', 'Other')], default='other', max_length=50)),
                ('reaction_details', models.TextField(blank=True)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_allergies', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'Patient Allergies',
                'ordering': ['-severity', 'allergen'],
            },
        ),
        migrations.CreateModel(
            name='PatientChronicDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200)),
                ('icd10_code', models.CharField(blank=True, max_length=20)),
                ('diagnosed_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('controlled', 'Controlled'), ('remission', 'Remission'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosed_diseases', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronic_diseases', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Chronic Disease',
                'verbose_name_plural': 'Chronic Diseases',
                'ordering': ['-diagnosed_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientMedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=200)),
                ('icd10_code', models.CharField(blank=True, max_length=20)),
                ('diagnosed_date', models.DateField(blank=True, null=True)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'Medical History',
                'ordering': ['-diagnosed_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientSurgicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_name', models.CharField(max_length=200)),
                ('surgery_date', models.DateField()),
                ('hospital', models.CharField(blank=True, max_length=200)),
                ('surgeon', models.CharField(blank=True, max_length=200)),
                ('indication', models.TextField(blank=True)),
                ('complications', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'Surgical History',
                'ordering': ['-surgery_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientVaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=200)),
                ('dose_number', models.PositiveIntegerField()),
                ('date_administered', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('facility_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_vaccines', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='patients.patient')),
            ],
            options={
                'ordering': ['-date_administered'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['patient_number'], name='patients_pa_patient_f07fc4_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['mrn_number'], name='patients_pa_mrn_num_4f4661_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['first_name', 'last_name'], name='patients_pa_first_n_a142c0_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone_primary'], name='patients_pa_phone_p_dd7e42_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['identification_number'], name='patients_pa_identif_45e19b_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['nhif_number'], name='patients_pa_nhif_nu_c9a752_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['county'], name='patients_pa_county_c49503_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['created_at'], name='patients_pa_created_542792_idx'),
        ),
    ]
