# Generated by Django 6.0.5 on 2026-06-03 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('admission_type', models.CharField(choices=[('emergency', 'Emergency Admission'), ('elective', 'Elective Admission'), ('transfer', 'Transfer from another facility'), ('postnatal', 'Postnatal Admission'), ('antenatal', 'Antenatal Admission')], max_length=20)),
                ('primary_diagnosis', models.TextField()),
                ('secondary_diagnosis', models.TextField(blank=True)),
                ('admitting_notes', models.TextField()),
                ('condition_on_admission', models.TextField()),
                ('status', models.CharField(choices=[('admitted', 'Admitted'), ('in_treatment', 'In Treatment'), ('stable', 'Stable'), ('critical', 'Critical'), ('discharged', 'Discharged'), ('transferred', 'Transferred'), ('expired', 'Expired'), ('absconded', 'Absconded')], default='admitted', max_length=20)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('expected_discharge_date', models.DateField(blank=True, null=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('discharge_status', models.CharField(blank=True, choices=[('home', 'Discharged Home'), ('transfer', 'Transferred to Another Facility'), ('ama', 'Discharged Against Medical Advice'), ('deceased', 'Deceased'), ('absconded', 'Absconded')], max_length=20)),
                ('discharge_summary', models.TextField(blank=True)),
                ('discharge_instructions', models.TextField(blank=True)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transferred_from', models.CharField(blank=True, max_length=200)),
                ('transferred_to', models.CharField(blank=True, max_length=200)),
                ('transfer_reason', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('admitting_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions_made', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admissions', to=settings.AUTH_USER_MODEL)),
                ('discharged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharges', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patients.patient')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='visits.visit')),
            ],
            options={
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=20)),
                ('bed_type', models.CharField(choices=[('standard', 'Standard'), ('icu', 'ICU Bed'), ('pediatric', 'Pediatric Bed'), ('maternity', 'Maternity Bed'), ('isolation', 'Isolation Bed'), ('bariatric', 'Bariatric Bed')], default='standard', max_length=20)),
                ('is_occupied', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('is_under_maintenance', models.BooleanField(default=False)),
                ('has_oxygen_outlet', models.BooleanField(default=False)),
                ('has_suction_outlet', models.BooleanField(default=False)),
                ('has_call_bell', models.BooleanField(default=True)),
                ('has_side_rails', models.BooleanField(default=True)),
                ('has_overbed_table', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bed', to='admissions.admission')),
                ('current_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_bed', to='patients.patient')),
            ],
            options={
                'ordering': ['ward', 'bed_number'],
            },
        ),
        migrations.AddField(
            model_name='admission',
            name='bed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='admissions.bed'),
        ),
        migrations.CreateModel(
            name='DailyRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjective', models.TextField(help_text="Patient's complaints today")),
                ('objective', models.TextField(help_text='Physical examination findings')),
                ('assessment', models.TextField(help_text='Current assessment')),
                ('plan', models.TextField(help_text="Today's treatment plan")),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.IntegerField(blank=True, null=True)),
                ('medication_changes', models.TextField(blank=True)),
                ('investigations_ordered', models.TextField(blank=True)),
                ('diet_ordered', models.CharField(blank=True, max_length=200)),
                ('round_date', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='admissions.admission')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-round_date'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('ward_type', models.CharField(choices=[('general', 'General Ward'), ('private', 'Private Ward'), ('vip', 'VIP Suite'), ('icu', 'Intensive Care Unit'), ('hdu', 'High Dependency Unit'), ('pediatric', 'Pediatric Ward'), ('maternity', 'Maternity Ward'), ('isolation', 'Isolation Ward'), ('psychiatric', 'Psychiatric Ward'), ('rehabilitation', 'Rehabilitation')], max_length=20)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('building', models.CharField(blank=True, max_length=100)),
                ('total_beds', models.IntegerField()),
                ('available_beds', models.IntegerField()),
                ('occupied_beds', models.IntegerField(default=0)),
                ('has_oxygen', models.BooleanField(default=True)),
                ('has_suction', models.BooleanField(default=True)),
                ('has_monitoring', models.BooleanField(default=False)),
                ('has_private_bathroom', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_under_maintenance', models.BooleanField(default=False)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('in_charge_nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incharge_wards', to=settings.AUTH_USER_MODEL)),
                ('ward_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_wards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='admissions.ward'),
        ),
        migrations.AddField(
            model_name='admission',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='admissions.ward'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('ward', 'bed_number')},
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['admission_number'], name='admissions__admissi_9dcc3e_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['patient', 'status'], name='admissions__patient_89630d_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['admission_date'], name='admissions__admissi_f4dd53_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['ward', 'status'], name='admissions__ward_id_682b01_idx'),
        ),
    ]
