# Generated by Django 6.0.5 on 2026-06-03 09:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('visit_type', models.CharField(choices=[('outpatient', 'Outpatient'), ('inpatient', 'Inpatient'), ('emergency', 'Emergency'), ('consultation', 'Consultation'), ('follow_up', 'Follow-up'), ('antenatal', 'Antenatal Care'), ('postnatal', 'Postnatal Care'), ('wellness', 'Wellness Check'), ('telemedicine', 'Telemedicine'), ('home_visit', 'Home Visit')], default='outpatient', max_length=20)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('check_in', 'Checked In'), ('triage', 'In Triage'), ('waiting', 'Waiting'), ('consultation', 'In Consultation'), ('investigation', 'Under Investigation'), ('treatment', 'Under Treatment'), ('observation', 'Under Observation'), ('admitted', 'Admitted'), ('discharged', 'Discharged'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='registered', max_length=20)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency'), ('critical', 'Critical')], default='routine', max_length=20)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('triage_time', models.DateTimeField(blank=True, null=True)),
                ('consultation_start', models.DateTimeField(blank=True, null=True)),
                ('consultation_end', models.DateTimeField(blank=True, null=True)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('waiting_time_triage', models.IntegerField(default=0, help_text='Minutes waited for triage')),
                ('waiting_time_consultation', models.IntegerField(default=0, help_text='Minutes waited for consultation')),
                ('total_waiting_time', models.IntegerField(default=0, help_text='Total waiting time in minutes')),
                ('chief_complaint', models.TextField()),
                ('history_of_present_illness', models.TextField(blank=True)),
                ('review_of_systems', models.JSONField(blank=True, default=dict)),
                ('past_medical_history', models.TextField(blank=True)),
                ('family_history', models.TextField(blank=True)),
                ('social_history', models.TextField(blank=True)),
                ('provisional_diagnosis', models.TextField(blank=True)),
                ('final_diagnosis', models.TextField(blank=True)),
                ('icd10_codes', models.JSONField(blank=True, default=list)),
                ('differential_diagnosis', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('procedures_performed', models.JSONField(blank=True, default=list)),
                ('outcome', models.TextField(blank=True)),
                ('discharge_instructions', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('insurance', 'Insurance'), ('waived', 'Waived'), ('bad_debt', 'Bad Debt')], default='pending', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insurance_claim_number', models.CharField(blank=True, max_length=100)),
                ('is_emergency', models.BooleanField(default=False)),
                ('requires_admission', models.BooleanField(default=False)),
                ('requires_referral', models.BooleanField(default=False)),
                ('is_telemedicine', models.BooleanField(default=False)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('referred_from', models.CharField(blank=True, max_length=200)),
                ('referred_to', models.CharField(blank=True, max_length=200)),
                ('referral_reason', models.TextField(blank=True)),
                ('clinical_notes', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_visits', to=settings.AUTH_USER_MODEL)),
                ('clinical_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_visits', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visits', to=settings.AUTH_USER_MODEL)),
                ('follow_up_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_visits', to=settings.AUTH_USER_MODEL)),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_visits', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
                ('primary_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_visits', to=settings.AUTH_USER_MODEL)),
                ('referring_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registration_time'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('progress', 'Progress Note'), ('doctor', "Doctor's Note"), ('nurse', "Nurse's Note"), ('discharge', 'Discharge Summary'), ('referral', 'Referral Note'), ('consultation', 'Consultation Note')], max_length=20)),
                ('subjective', models.TextField(help_text="Patient's symptoms and complaints")),
                ('objective', models.TextField(help_text='Physical exam findings and test results')),
                ('assessment', models.TextField(help_text='Diagnosis and assessment')),
                ('plan', models.TextField(help_text='Treatment plan and next steps')),
                ('review_of_systems', models.JSONField(blank=True, default=dict)),
                ('physical_examination', models.JSONField(blank=True, default=dict)),
                ('investigations', models.JSONField(blank=True, default=list)),
                ('medications_prescribed', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_notes_detail', to='visits.visit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='°C', max_digits=4, null=True)),
                ('pulse_rate', models.IntegerField(blank=True, help_text='beats/min', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('respiratory_rate', models.IntegerField(blank=True, help_text='breaths/min', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('systolic_bp', models.IntegerField(blank=True, help_text='mmHg', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('diastolic_bp', models.IntegerField(blank=True, help_text='mmHg', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('oxygen_saturation', models.IntegerField(blank=True, help_text='%', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('blood_glucose', models.DecimalField(blank=True, decimal_places=2, help_text='mmol/L', max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('pain_score', models.IntegerField(blank=True, help_text='0-10 scale', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('pain_location', models.CharField(blank=True, max_length=200)),
                ('glasgow_coma_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(15)])),
                ('avpu_score', models.CharField(blank=True, help_text='A=Alert, V=Verbal, P=Pain, U=Unresponsive', max_length=1)),
                ('fundal_height', models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=5, null=True)),
                ('fetal_heart_rate', models.IntegerField(blank=True, null=True)),
                ('contractions', models.CharField(blank=True, max_length=100)),
                ('head_circumference', models.DecimalField(blank=True, decimal_places=2, help_text='cm', max_digits=5, null=True)),
                ('muac', models.DecimalField(blank=True, decimal_places=2, help_text='Mid-Upper Arm Circumference (cm)', max_digits=5, null=True)),
                ('vitals_notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_vitals', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='visits.visit')),
            ],
            options={
                'verbose_name_plural': 'Vitals',
            },
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['visit_number'], name='visits_visi_visit_n_c2f230_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['patient', 'status'], name='visits_visi_patient_928711_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['registration_time'], name='visits_visi_registr_865d08_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['status', 'priority'], name='visits_visi_status_262009_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['primary_doctor', 'status'], name='visits_visi_primary_76062b_idx'),
        ),
        migrations.AddIndex(
            model_name='vitals',
            index=models.Index(fields=['visit'], name='visits_vita_visit_i_e70385_idx'),
        ),
        migrations.AddIndex(
            model_name='vitals',
            index=models.Index(fields=['recorded_at'], name='visits_vita_recorde_01214e_idx'),
        ),
    ]
